version: "2"
services:
    app:
        image: app:v1
        ports: 
            - "80:80"
        links:
            - db
        networks:
            - default
    db:
        image: db:v1
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: sample
            MYSQL_USER: sampleuser
            MYSQL_PASSWORD: samplepass
            MYSQL_ROOT_PASSWORD: Jbbu#LX4bY4h
        networks:
            - default
